### ISSUE TITLE
Pod Housekeeping Page--User Just Joined

### ISSUE THREAD

**Issue by OmneBonum** [OmneBonum/voting-portal-2.0#12]
When a user enters a valid key and is taken to the Housekeeping page, show a message above the Member List. "[Legal Name] you are now a candidate to join Pod ######. To become a voting member you will need a majority of votes from the existing members. You should be in touch with [Legal Name First Delegate] who should be coordinating the vote. They can let you know when you have received enough votes. Them. refresh this page and you will see you have been added to the list of members.  Congratulations!"

**Comment by zamanehsani** [comment]
I think is is being addresses in the Status section of the Housekeeping page.
